format = "$directory$git_branch$git_status$character"
right_format = "$time"

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"

[directory]
format = "[$path](cyan) "

[git_branch]
format = "[$branch](purple) "

[git_status]
format = "[$all_status](red)"

[time]
disabled = false
format = "[$time](white)"
time_format = "%H:%M"
